### ISSUE TITLE
Upgraded plugin to the latest NXRM 3.36.0

### ISSUE THREAD

**Issue by luistilingue** [sonatype-nexus-community/nexus-blobstore-google-cloud#106]
Hi.

Could you provide a plugin version for the latest version of Nexus, 3.36.0?

Thanks.

**Comment by nblair** [comment]
Hi @luistilingue - looks like I'm two versions behind, I need to get caught up. I'll try to publish packages shortly.

**Comment by nblair** [comment]
New versions are available for 3.35 and 3.36.
