### ISSUE TITLE
Bump plugin to the NXRM 3.37.0

### ISSUE THREAD

**Issue by luistilingue** [sonatype-nexus-community/nexus-blobstore-google-cloud#109]
Hi,

Could you please upgrade plugin to the latest NXRM version?

Is there any way to do that automatically when a new NXRM version be released?

Thanks in advance.

**Comment by nblair** [comment]
Hi @luistilingue - thanks for reaching out. I have been preoccupied with other responsibilities, I apologize for the slow updates here. 
I would love and welcome a contribution to automatically update versions. Sometimes, it's super easy; https://github.com/sonatype-nexus-community/nexus-blobstore-google-cloud/commit/8e77226df176331f9001fe3ce63957c9dcbccddb is an example where there were no changes to the Nexus Repository Manager APIs.

Sometimes it's less easy, as a new APIs might show up that need to be implemented. I'd love to automate that simple step along with execution of the integration tests to make quick releases.

**Comment by nblair** [comment]
https://github.com/sonatype-nexus-community/nexus-blobstore-google-cloud/releases/tag/nexus-blobstore-google-cloud-parent-0.37.0 is now available.
