### ISSUE TITLE
GCP plugin installation in Nexus for kubernetes

### ISSUE THREAD

**Issue by ep4sh** [sonatype-nexus-community/nexus-blobstore-google-cloud#110]
* **What are you trying to do?**
I'm trying to understand if it is possible to install Nexus in Kubernetes with nexus-blobstore-google-cloud
  (using official helm) without container image recreation? 
 As far as I understood GCS plugin is a ".kar " and should be installed on the filesystem...

* **What feature or behavior is this required for?**

I'd like to use Nexus and GCS (google cloud storage) as storage-backend, the same 

* **How could we solve this issue? (Not knowing is okay!)**
Meow? =\
well, I saw very similar thing was done in Sonarqube installation helm chart (you just specify HTTP URLs for plugins)

* **Anything else?**
Thank you ^^

**Comment by nblair** [comment]
Hi @ep4sh! Thanks for reaching out. 
I don't have a strong understanding of Kubernetes, so pardon my naivete. You're right in that this plugin is distributed as a separate archive that must be added to an NXRM install.

The Dockerfile shows the HTTPS URL where the plugin can be downloaded from Maven Central:

https://github.com/sonatype-nexus-community/nexus-blobstore-google-cloud/blob/main/Dockerfile#L9

I am not currently publishing an image to dockerhub that can be pulled that already has this step. For my deployments, I build and deploy a local image to a hosted repository, and pull from there. Does that help?

**Comment by ep4sh** [comment]
Thank you @nblair, yeah, it helped a lot!
