### ISSUE TITLE
Bump plugin to the NXRM 3.37.3

### ISSUE THREAD

**Issue by luistilingue** [sonatype-nexus-community/nexus-blobstore-google-cloud#111]
Please, bump plugin to the NXRM 3.37.3.

**Comment by nblair** [comment]
Out of curiosity, does the latest 0.37 version of the plugin fail to deploy on 3.37.3? It targets 3.37.1 for compile, there aren't any material runtime changes from there and 3.37.3.

**Comment by nblair** [comment]
I can confirm the latest version will deploy successfully on 3.37.3. I'll bump the Dockerfile in this repository to bump it forward, but no plugin code changes are required to be compatible for 3.37.1-3.37.3.
