### ISSUE TITLE
Upgrade 3.39

### ISSUE THREAD

**Issue by luistilingue** [sonatype-nexus-community/nexus-blobstore-google-cloud#115]
Could you please upgrade that plugin to the latest version 3.39.0?

**Comment by nblair** [comment]
Took a quick look - there are some new API methods that need to be implemented in 3.39, so it won't be a trivial bump forward. I'll need to find some time to work on the upgrade.

**Comment by luistilingue** [comment]
Any news, @nblair ?

**Comment by nblair** [comment]
Upgrading to 3.39 brings with a number of transitive dependency updates that will need some changes to adapt. The new methods in the API are likely to have no-op implementations, but getting the unit and integration tests functional again will add some delays.
