### ISSUE TITLE
Migration of blobs from existing nexus instance to gcp bucket

### ISSUE THREAD

**Issue by manish-nference** [sonatype-nexus-community/nexus-blobstore-google-cloud#117]
* **What are you trying to do?**
I have migrated the entire nexus instance to GCP and using your plugin. Everything works fine. 

I have some hosted repos in the file blob vol-chap format and see content directory in gcp bucket as well. 
Now how do I move these existing file blobs to GCP bucket so that nexus would know where to pick up. I already changed the metadata of blob storage to buckets.

Is this something which is possible by this plugin?

**Comment by nblair** [comment]
While the directory format looks similar, migrating content from file backed blobstores to this plugin is not presently supported.

**Comment by manish-nference** [comment]
While I see the AWS S3 plugin they have a specific column like prefix . What if we can have something of sort in this plugin and then change the blob storage to that specific location instead of pointing to one default bucket root position. 

Just thinking would something like this work?

**Comment by nblair** [comment]
I would not recommend trying to do this with live data unless you are willing to lose it. I suspect you would need to develop some support for that capability within this plugin.

**Comment by manish-nference** [comment]
yeah, I was thinking something within this plugin only. Thanks for the clarification
