### ISSUE TITLE
ITs are not run in any CI

### ISSUE THREAD

**Issue by jtnord** [sonatype-nexus-community/nexus-blobstore-google-cloud#128]
the ITs do not appear to be run in circle or Jenkins.

This adds load to the maintainers and makes community contributions more onerous.

The CI should (when approved - e.g. like the approval release gate workflow in circle ci) run ITs against a test account to validate things are working as expected.

This will bring benifits as things like renovate or dependabot could be easily setup to ensure that the plugin is built against and is compatable with the the most recently released nexus verions.

relates to #127 127

**Comment by nblair** [comment]
The ITs that exist in the project were useful in the early stages, but over time definitely decayed. I rarely made use of them myself; internally Sonatype has been moving to a different way to perform end to end testing for all of the product capabilities.

We didn't have any dedicated CI infrastructure for community projects, as early attempts to do so were often met with attempts to compromise said infrastructure with malicious pull requests. My apologies for being unable to provide this feature.

**Comment by madpah** [comment]
ℹ️ As of 7th November 2024, this community project has [graduated](https://contribute.sonatype.com/docs/project-classification/) and is offered as part of Sonatype's commercial offerings - see [here](https://help.sonatype.com/en/configuring-blob-stores.html#google-cloud-blob-store) for full details.

🚧 This community project will receive not accept further contributions nor receive maintenance.
