### ISSUE TITLE
Time to sunset

### ISSUE THREAD

**Issue by nblair** [sonatype-nexus-community/nexus-blobstore-google-cloud#132]
Hey all - I'm @nblair, the original author and primary maintainer for this community contribution. I am a current Sonatyper, and this side project has been a labor of love for some of my time here.

I wanted to share the news here that it's my intention to sunset this project. 

Sonatype has this internal cultural aspect called "Improvement Day." The goal of Improvement Day is for each staff member to set aside 10% of their time (i.e., every other Thursday) for any improvement they feel will benefit them AND Sonatype. 

This project first debuted inside Sonatype in November of 2017 on Improvement Day. Myself and a few others iterated until we had something working, and we were allowed to license and distribute the code here in the community in May of 2018.

This project really helped me achieve that primary goal - I learned a lot about Google Cloud and really helped me develop expand my expertise in contributing to Nexus Repository. I'm thankful for the experience it gave me and I hope that others found it useful. 

This week is another big milestone - support for Google Cloud Storage and other aspects of Google Cloud are now officially supported in Sonatype Nexus Repository Pro, see the [release notes](https://help.sonatype.com/en/sonatype-nexus-repository-3-74-0-release-notes.html). 

The official supported version is notably different from this version and has full support for H2 and PostgreSQL databases (including High Availability configurations).

**Comment by madpah** [comment]
Thanks so much @nblair for all you did in this project!

Given the announcements in Sonatype Nexus Repository 3.74, we will work to mark this project as **GRADUATED** ahead of archival 😉
