### ISSUE TITLE
Need means to automatically create blobstore

### ISSUE THREAD

**Issue by steven-edgar** [sonatype-nexus-community/nexus-blobstore-google-cloud#23]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Create a blobstore automatically, so as to allow fully automated server buildout.

* **What feature or behavior is this required for?**
A script or API that can be called, with the appropriate parameters, to create the google cloud backed blobstore after the plugin has been installed.

* **How could we solve this issue? (Not knowing is okay!)**
Unknown, sorry.

* **Anything else?**

**Comment by nblair** [comment]
I may have a script for you to do this, let me see if I can craft it up and share a gist, or add something here.

**Comment by nblair** [comment]
Are you familiar with the [Script API](https://help.sonatype.com/repomanager3/rest-and-integration-api/script-api)?

I've posted a gist with a small script you would need to upload and execute in a running NXRM instance after installing the Google Cloud Blobstore plugin:

https://gist.github.com/nblair/64e1e33b2b4bde0700c36fe73b264d3e

Let me know how it goes!

**Comment by nblair** [comment]
I'll close this issue for now - please feel free to re-open or create a new if the aforementioned script needs some help. Thanks!

**Comment by steven-edgar** [comment]
Apologies for the delay in getting back to you. I made a few tweaks to your groovy script, mostly to enable passing in arguments and being able to re-run it without causing an error due to the blobstore already existing. It could probably do with further extension to allow updating an existing blobstore, but don't suppose that's very useful, for us at least. Thanks a lot for the response, I had no idea how to do this before.

**Comment by nblair** [comment]
Glad to hear you've got it working! I'd love to see the improvements to the script if you're willing to share.

**Comment by steven-edgar** [comment]
Hi, I posted them as a comment underneath your gist.
