### ISSUE TITLE
Build fails with latest maven docker image

### ISSUE THREAD

**Issue by tonyfahrion** [sonatype-nexus-community/nexus-blobstore-google-cloud#27]
Hi,

* **What are you trying to do?**
* I tryed to build the plugin via docker build

* **How could we solve this issue?**
* pinning to JDK 8; it seems that this plugin won't compile with JDK 13, which is the version provided by `maven:latest`

* **Anything else?**
Error message with JDK 13:

```
```
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /build/nexus-blobstore-google-cloud-0.4.0/src/main/java/org/sonatype/nexus/blobstore/gcloud/internal/GoogleAttributesLocation.java:[1,1] 1. ERROR in /build/nexus-blobstore-google-cloud-0.4.0/src/main/java/org/sonatype/nexus/blobstore/gcloud/internal/GoogleAttributesLocation.java (at line 1)
	package org.sonatype.nexus.blobstore.gcloud.internal;
	^
The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files

[ERROR] /build/nexus-blobstore-google-cloud-0.4.0/src/main/java/org/sonatype/nexus/blobstore/gcloud/internal/GoogleAttributesLocation.java:[1,1] 2. ERROR in /build/nexus-blobstore-google-cloud-0.4.0/src/main/java/org/sonatype/nexus/blobstore/gcloud/internal/GoogleAttributesLocation.java (at line 1)
	package org.sonatype.nexus.blobstore.gcloud.internal;
	^
The type java.lang.String cannot be resolved. It is indirectly referenced from required .class files

[ERROR] /build/nexus-blobstore-google-cloud-0.4.0/src/main/java/org/sonatype/nexus/blobstore/gcloud/internal/GoogleAttributesLocation.java:[9,14] 3. ERROR in /build/nexus-blobstore-google-cloud-0.4.0/src/main/java/org/sonatype/nexus/blobstore/gcloud/internal/GoogleAttributesLocation.java (at line 9)
```

**Comment by mattjohnson** [comment]
Hi @tonyfahrion I confirmed I have the same issue. I tried pinning to JDK8 but also ran into issues with that. Hopefully I'll have it resolved soon. Also I plan on adding the build to the CI build so we'll catch this type of issue sooner.

**Comment by tonyfahrion** [comment]
I added the following line to the build image:
```
RUN apk add --no-cache git && \
       git clone ${GOOGLE_PLUGIN_URL} --branch=${GOOGLE_PLUGIN_VERSION} --depth 1 . && \
       mvn clean package
```

I am not removing git later, because it's just the build image and gets dropped later anyway

**Comment by mattjohnson** [comment]
Yeah, I agree with changing from install to package. No need to run tests. I also think it should build the current workspace and not latest from master. Seems like some indirection there. I opened a [PR](https://github.com/sonatype-nexus-community/nexus-blobstore-google-cloud/pull/28) with some changes that should resolve this.

**Comment by nblair** [comment]
👍 thanks for raising. I might not get to look at it for a day or so, feel free to PR if you've got a spare moment or two.

**Comment by tonyfahrion** [comment]
very cool 🙂 Thank you!
