### ISSUE TITLE
Migrate Datastore usage to Firestore

### ISSUE THREAD

**Issue by nblair** [sonatype-nexus-community/nexus-blobstore-google-cloud#39]
[Google Firestore](https://cloud.google.com/firestore/) is the next generation service to Datastore.

Firestore supports Datastore backwards compatibility and has fewer transaction limits than Datastore does.

Quickstart document: https://cloud.google.com/firestore/docs/quickstart-servers

**Comment by goloxxly** [comment]
Could you please outline which parts would be affected by this change? So that I could see how large the work would be.

**Comment by nblair** [comment]
At present, it appears the plugin fully supports Firestore in Datastore mode (see https://github.com/sonatype-nexus-community/nexus-blobstore-google-cloud/releases/tag/0.9.2). I don't see a reason to switch to Firestore native mode per this document:

https://cloud.google.com/firestore/docs/firestore-or-datastore

**Comment by goloxxly** [comment]
My problem is that we're already using Firestore in native mode and as the above doc says:

> Warning: Once you select a database mode and execute the first write on the database, you cannot switch. You can't use both Native Mode and Datastore Mode in the same project.

**Comment by nblair** [comment]
@goloxxly this is true, you can't switch between modes or host both in the same project. It is possible however to have multiple projects within one Google Account. I'm curious to know if migrating the host to a separate project is something feasible to try? I understand it is possible to migrate the host VM and storage bucket(s).

Firestore native mode doesn't appear to be the best fit for this project as it appears to target mobile development; whereas Datastore mode is targeted for server-side applications like this. The other benefit to datastore mode is cost - the operations performed by this plugin using the Datastore APIs are considered "Small Operations", which are free; Firestore native does not have any equivalent free operations.
