### ISSUE TITLE
Future changes to make the plugin more adoptable

### ISSUE THREAD

**Issue by akettmann-e24** [sonatype-nexus-community/nexus-blobstore-google-cloud#68]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Adopt using GCS backed blobstores
* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**
The main problems I see are the following:

- no migration path from on disk to blobstore - this makes it only practical for new repos or new users of nexus
- Acct needs some over-reaching perms (Storage admin and datastore admin for entire project)

We have an existing nexus instance that is using on disk blobs and I would like to back it with GCS but the two issues above are sadly a deal breaker for us.
* **Anything else?**
One common thing we internally have found is that the GCP Java examples tend to ask you to do things like list buckets and the like which require older or more all encompassing permissions. 

Generally the examples in Python go by the idea of "assume you have the rights to something". So maybe instead of listing the buckets in the project, assume the bucket name given already exists and assume you have access to it, but handle the exceptions raised if you don't and show notifications accordingly. 

Or perhaps another option would be to allow a configuration setting to point at another project. Due to networking limitations in GCP we must have the instance in a specific project to have it accessible, but that means it is with other things that have to be in this project, so the storage admin role being granted to this instance is not something we can do reasonably.

**Comment by akettmann-e24** [comment]
Oh just to clarify, the no migration path without a subscription is a problem that is not specific to this plugin, so I didn't really expand on that much.

**Comment by nblair** [comment]
Hi @akettmann-e24 - thank you again, this is great concrete feedback :)

With regards to migrating File Blobstores to other forms (S3 or this plugin), there is a Pro-only capability built in to Repository Manager using the Group Blobstore feature. This is covered in more detail at https://blog.sonatype.com/dynamic-storage-improvements-3.15. 
While the file layouts between this plugin and File Blobstores are similar, there's a fair bit more complexity migrating the asset references in the RM database. That complexity is out of scope for this plugin. Migration runtime is often a big factor too; long stop-the-world downtime for RM isn't possible for many deployers, so the Pro feature covers still making that content accessible while being moved. 
If Pro isn't an option, consider instance-to-instance migration strategies like was mentioned in https://github.com/sonatype-nexus-community/nexus-blobstore-google-cloud/issues/55#issuecomment-580948456. I'm sorry we can't do more natively in the plugin.

 I definitely agree about the concerns about privileges for Datastore and Storage admin. Tightening that up to least privileges is on my wish list as the plugin matures. Would you mind if I split your feedback here into two new issues, one focusing on the privileges for each of those GCP services?

**Comment by akettmann-e24** [comment]
That sounds perfect! I love the idea of this plugin, and definitely appreciate efforts towards getting some more parity between AWS and GCS clouds. Also we have had very similar issues with our internal Java developers getting started with GCS where the examples suggest you do stuff that requires absurd privs. Glad I could give some good feedback!

**Comment by nblair** [comment]
Excellent - I've opened #69 and #70 to track the permission improvements. I can't commit to a specific timeline, as I work on this as time permits, but I will push it up to the top of the queue for me. Contributions are welcome as well!

**Comment by akettmann-e24** [comment]
I don't actually write any java myself, python or golang mostly so unfortunately I am not much help here, I am glad my input was valuable though!
________________________________
