### ISSUE TITLE
Should Datastore be optional?

### ISSUE THREAD

**Issue by nblair** [sonatype-nexus-community/nexus-blobstore-google-cloud#74]
[Datastore](https://cloud.google.com/datastore) is used by this plugin for storing blobstore metadata:

* the count and total size of assets in the blobstore
* the list of "soft deleted" assets that can be reclaimed later by a scheduled task.

The use of Datastore for these purposes has a number of benefits, primarily in terms of performance, accuracy, and support for High Availability Clustering (Nexus Repository Manager Pro only). [Design documentation](design/datastore_for_blobstore_metadata.md).

The use of Datastore is also the primary source of issues raised by the community (#51, #55, #61, #63, #73).

The code for storing this metadata back within text files inside the storage bucket is easy to restore back into the plugin. This would be at a loss of performance (I can test internally to confirm), but it would simplify the service account permissions and setup.

I'm opening this issue to solicit feedback from the community:

Would you like the option of choosing between object storage and datastore for this metadata?

**Comment by nblair** [comment]
I did some research through older releases and it turns out that Datastore was in use for the deleted blobs index from the first public release (https://github.com/sonatype-nexus-community/nexus-blobstore-google-cloud/blob/0.2.0/src/main/java/org/sonatype/nexus/blobstore/gcloud/internal/DeletedBlobIndex.java). At the time, Datastore was a separate service offering from Firestore.

**Comment by tonyfahrion** [comment]
Hi nblair,

this would be really helpful. We are also trying to avoid the Firestore integration right now, this is why I stumbled over this issue 🙂 

A cheaper solution would be to depend on something like redis. Especially because it is easy to deploy within a Kubernetes instance as a companion service.

(just to give some feedback :))

Have a wonderful time!
Tony

**Comment by nblair** [comment]
Thanks for the feedback! I hadn't considered trying to move the data into a companion service. I am concerned that adding redis as a requirement for deploying the plugin would be seen as a barrier to entry.

An alternative thought experiment: 
 
* How important is the data about the size of the blobstore? What if the admin panel said "unknown" for size/count instead?
* What if the plugin performed hard deletes instead of soft deletes? Are the assets being stored impossible to reproduce?

One possible goal would be a Google Cloud Storage-only plugin, that required no companion services, or compromises/reduced functionality for the aforementioned items.

**Comment by tonyfahrion** [comment]
For the second (hard vs. soft delete) option it might be an interesting concept as GCS supports versioning and via lifecycle settings people can delete "non-live" files by their very own schedule. Like "delete files from versions that do not have a live version after 14 days".

But I do not know what this might mean for nexus internally.

**Comment by nblair** [comment]
Thanks for the tip @tonyfahrion - I'm going to queue up some discovery to see if object lifecycle will work. I believe the AWS S3 blobstore already does this with similar lifecycle functions .

**Comment by nblair** [comment]
@tonyfahrion if you have some time, I'd appreciate some feedback on the approach I'm thinking about for this - please take a look at #81, I'd love to hear if you think it would work.

**Comment by nblair** [comment]
Closing the feedback loop on this. There is a capability within Nexus Repository we can leverage that uses the internal database instead. A future effort to use that capability - and potentially migrate any data already in datastore - should be considered.
