### ISSUE TITLE
Very slow upload throughput to a bucket

### ISSUE THREAD

**Issue by luistilingue** [sonatype-nexus-community/nexus-blobstore-google-cloud#93]
Hi.

I'm facing very slow upload throughput to a bucket, even enabling multipart upload (nearly identical performance).

My GCS Blobstore has 1.6TB (maven and npm repositories), although the speed is the same since empty. Please check the maven build screenshot:
![image](https://user-images.githubusercontent.com/61065171/110794820-e83b5b80-8254-11eb-8d70-8a71ee8b19ec.png)

These artifacts are very small (dozens of KB only - 50KB, 20KB, etc)

**NXRM**: 3.30 (but the same upload speed since 3.28)
**Resources**: Running on k8s GKE. 4vCPU and 6Gi RAM (the pod stay almost 'sleeping' even in many concurrent usage).
**Plugin**: 0.20

![image](https://user-images.githubusercontent.com/61065171/110794211-461b7380-8254-11eb-9c45-91c58f721461.png)
![image](https://user-images.githubusercontent.com/61065171/110794310-5f242480-8254-11eb-9143-8436c6af6099.png)

**Comment by nblair** [comment]
Thanks for opening @luistilingue - I'll try to help the best I can. Troubleshooting throughput can often be complex and take a lot of back and forth before we get to root cause. It's worth starting off that the throughput is never going to be as high as writing to local disk, as the data has to go through HTTPS instead of a more efficient I/O channel.

I'll start by asking - is this Nexus Repository Manager instance hosted in Google Cloud, and if so in a nearby region to the bucket? 
Where is the client in relationship to this instance? Is it too in Google Cloud? Same region? If not, how geographically distant?

**Comment by luistilingue** [comment]
Hi, @nblair .

As I told, it's running on **GKE**. Also it's running on a instance in **us-east1-b** and bucket is in **us-east.**

**Comment by nblair** [comment]
@luistilingue is the throughput you are seeing different in some way with the latest release than with previous releases?

On my side, I've spun up a stress test against the latest release. This test uses a number of parallel workers submitting read/write operations against a number of repositories of different types (including maven/npm) all using one Google Cloud Blobstore. The compute instance is a `n1-highmem-4`, running 3.30.0-01, on openjdk8 with a JVM min/max heap of `4G` and direct memory of `6717M`. CPU utilization on the host stays near 100% and we observe Network I/O around 96-100 MiB/s for the duration. 

The traffic ramps up quickly over the first minute and continues for 15 minutes. The end result is about 19,000 stored blobs totaling around 36 GB. The client side reports an average of around 39 successful requests per/second.

These numbers are pretty much in line with what I've observed in previous releases. 

I would not recommend using the parallel multipart upload feature, it's not going to provide any benefit for small artifacts.

**Comment by nblair** [comment]
Hi @luistilingue just curious if you have any more data on what you are observing?

**Comment by luistilingue** [comment]
@nblair I'm still seeing slow throughput (all previous releases/versions I've tested had the same behavior). The one thing different of your setup are the allocated resources. I'm using a small instance (although, the RAM and CPU usages are very stable - very below from limit).

**CPU**: 4
**Memory**: 8Gi (increased from 6Gi for testing since your last message)
**JVM min/max heap**: 2703M
**Direct memory**: 2703M

Anyway, thanks for support.

**Comment by nblair** [comment]
Hi @luistilingue - I think it's worth mentioning that each individual artifact upload/download to Google Cloud Blobstores is going to take longer than upload/download to local disk. There is inherent latency in establishing the remote connection over http, streaming the bytes over the network, and handling the response. if you are comparing the individual upload/download experience to a File based Blobstore, there's no real fair comparison; local disk I/O is always going to be the lowest latency experience. Object storage backed blobstores (this, S3, Azure) are chosen for different requirements (easier provisioning with unlimited space, different backup/restore strategies, etc).
