### ISSUE TITLE
Revert back to local disks

### ISSUE THREAD

**Issue by dejablue79** [sonatype-nexus-community/nexus-blobstore-google-cloud#94]
Not yet an issue, But is there a way to move data, currently in Google Storage, back to local disks?

**Comment by nblair** [comment]
Hi @dejablue79 - you can't just take the files from the bucket back to a local disk. There is a Nexus Repository Manager Pro feature that can help you move content from one blobstore to another: https://help.sonatype.com/repomanager3/system-configuration/tasks/change-repository-blob-store. I hope this helps!
