### ISSUE TITLE
Upgrade plugin to the latest version of NXRM

### ISSUE THREAD

**Issue by luistilingue** [sonatype-nexus-community/nexus-blobstore-google-cloud#95]
Hi.

Could you please make a upgrade in plugin for the latest version 3.31.0?

Is there any way for automatic build when a new version of NXRM be released? It'd be awesome.

Thanks.

**Comment by nblair** [comment]
I'll take a look at the upgrade in the next few days.

**Comment by nblair** [comment]
I started the upgrade and it appears there are 2 new methods that the blobstore needs to implement in order to be compatible with 3.31. That rules out an easy automatic increment of the version for this release at least.
