### ISSUE TITLE
On K8S save and restore repository data & blob store config

### ISSUE THREAD

**Issue by jumanzi** [sonatype-nexus-community/nexus-blobstore-google-cloud#97]
Hi guys, 
I'm trying to provision private docker registry on GKE.
thing is, after it redeploy nexus pods, it lost repository data & blob store data.

is there any way to save and restore this config?

Thanks in advance. this plugin really helps a lot!

**Comment by nblair** [comment]
Hi @jumanzi - the Dockerfile provided here is built from Sonatype's image for Nexus 3. Take a look at the [documentation on Persistent Data](https://github.com/sonatype/docker-nexus3#persistent-data) - you will need to provide a persistent volume for the instances local configuration if you would like the database to persist between container restarts.

**Comment by nblair** [comment]
Hi @jumanzi was that documentation helpful? I'll close the ticket in a day if you have no further questions.

**Comment by jumanzi** [comment]
@nblair 
Sorry for late reply.
I mounted PV for nexus-data directory, and it works well. thanks for sharing the link.
